export const MODAL_ID = {
  ADD_RECIPE_MODAL: 'ADD_RECIPE_MODAL',
  ADD_INGREDIENT_MODAL: 'ADD_INGREDIENT_MODAL',
  EDIT_RECIPE_MODAL: 'EDIT_RECIPE_MODAL',
  EDIT_INGREDIENT_MODAL: 'EDIT_INGREDIENT_MODAL',
  CONFIRMATION_MODAL: 'CONFIRMATION_MODAL',
  SETTINGS_MODAL: 'SETTINGS_MODAL',
  EXPORT_INGREDIENTS: 'EXPORT_INGREDIENTS',
  EXPORT_RECIPES: 'EXPORT_RECIPES',
} as const
