export const MODAL_ID = {
  ADD_RECIPE_MODAL: 'ADD_RECIPE_MODAL',
  ADD_INGREDIENT_MODAL: 'ADD_INGREDIENT_MODAL',
  EDIT_RECIPE_MODAL: 'EDIT_RECIPE_MODAL',
  EDIT_INGREDIENT_MODAL: 'EDIT_INGREDIENT_MODAL',
  CONFIRMATION_MODAL: 'CONFIRMATION_MODAL',
} as const
