import type { TranslationKeys } from './types'

const EnglishTranslations: Record<TranslationKeys, string> = {
  RECIPE_EXISTS: 'Recipe already exists.',
  INGREDIENT_EXISTS: 'Ingredient already exists.',
  SOMETHING_WENT_WRONG: 'Something went wrong. Please try again.',

  // General
  save: 'Save',
  add: 'Add',
  export: 'Export',
  edit: 'Edit',
  delete: 'Delete',
  remove: 'Remove',
  update: 'Update',
  yes: 'Yes',
  no: 'No',
  loading: 'Loading...',
  cancel: 'Cancel',
  filename: 'Filename',
  status: 'Status',
  title: 'Title',
  quantity: 'Quantity',
  units: 'Units',
  cost: 'Cost',
  produces: 'Produces',
  settings: 'Settings',
  created: 'Created',
  outOf: 'of',
  unitCost: 'Unit Cost',
  totalCost: 'Total Cost',
  addToRecipe: 'Add to Recipe',
  recipeUses: 'Recipe uses',
  close: 'Close',
  // Navigation
  recipes: 'Recipes',
  ingredients: 'Ingredients',
  recipe: 'Recipe',
  ingredient: 'Ingredient',

  // Recipe Management
  noDataAvailable: 'No Data Available',
  recipeName: 'Recipe Name',
  ingredientName: 'Ingredient Name',
  addNewRecipe: 'Add New Recipe',
  addNewIngredient: 'Add New Ingredient',
  addRecipe: 'Add Recipe',
  addIngredient: 'Add Ingredient',
  editRecipe: 'Edit Recipe',
  deleteRecipe: 'Delete Recipe',
  deleteIngredient: 'Delete Ingredient',
  confirmDeleteRecipe: 'Confirm Delete Recipe',
  confirmDeleteIngredient: 'Confirm Delete Ingredient',
  deleteRecipeConfirmation: 'Are you sure you want to delete this recipe? This action cannot be undone.',
  deleteIngredientConfirmation: 'Are you sure you want to delete this ingredient? This action cannot be undone.',
  editIngredient: 'Edit Ingredient',
  editIngredients: 'Edit Ingredients',
  addExisting: 'Add Existing',
  saveAndAddAnother: 'Save & Add another',
  addSubRecipe: 'Add Sub-Recipe',
  showInMenu: 'On Menu',
  filterToMenuItems: 'Only Menu Items',
  subRecipes: 'Sub Recipes',
  mainRecipes: 'Recipes',
  noDetails: 'No Details',
  unitsHelpText: 'Note - Units can only be set on creation',
  usedIn: 'Used In',

  // Form Labels and Placeholders
  ingredientNamePlaceholder: 'e.g. Flour, Salt, Olive Oil',

  // Status Values
  draft: 'Draft',
  published: 'Published',
  archived: 'Archived',

  // Messages
  recipeNotFound: 'Recipe not found.',
  ingredientNotFound: 'Ingredient not found.',
  errorLoadingRecipe: 'Error loading recipe.',
  errorLoadingRecipes: 'Error loading recipes.',
  errorLoadingIngredients: 'Error loading ingredients.',
  failedToAddIngredient: 'Failed to add ingredient.',
  errorAddingIngredient: 'Error adding ingredient.',

  // Loading States
  adding: 'Adding...',
  saving: 'Saving...',
  updating: 'Updating...',

  // Units
  units_singular: 'Unit',
  units_plural: 'Units',
  liters_singular: 'Liter',
  liters_plural: 'Liters',
  milliliters_singular: 'Milliliter',
  milliliters_plural: 'Milliliters',
  gallons_singular: 'Gallon',
  gallons_plural: 'Gallons',
  cups_singular: 'Cup',
  cups_plural: 'Cups',
  grams_singular: 'Gram',
  grams_plural: 'Grams',
  kilograms_singular: 'Kilogram',
  kilograms_plural: 'Kilograms',
  ounces_singular: 'Ounce',
  ounces_plural: 'Ounces',
  pounds_singular: 'Pound',
  pounds_plural: 'Pounds',
  pieces_singular: 'Piece',
  pieces_plural: 'Pieces',
  weightConversions: 'Weight Conversion Table',
  volumeConversions: 'Volume Conversion Table',
  unitConversions: 'Unit Conversion Tables',
  conversionDisclaimer: 'Conversions are approximate and based on US standard measurements',

  // Missing translations
  language: 'Language',
  english: 'English',
  spanish: 'Spanish',
  errorAddingRecipe: 'Error adding recipe.',
  errorAddingSubRecipe: 'Error adding sub-recipe.',
  failedToUpdateRecipe: 'Failed to update recipe.',
  errorUpdatingRecipe: 'Error updating recipe.',
  failedToUpdateIngredient: 'Failed to update ingredient.',
  errorUpdatingIngredient: 'Error updating ingredient.',
  all: 'All',
  none: 'None',
  select: 'Select',
  includeImages: 'Include Images',
  oneFilePerRecipe: 'One File Per Recipe',
  singlePDF: 'Single PDF',
  multiplePDFs: 'Multiple PDFs',
  searchRecipes: 'Search recipes...',

  // Data Management
  dataManagement: 'Data Management',
  databaseBackups: 'Database Backups',
  backupLocation: 'Backup location',
  exportAllData: 'Export All Data',
  restoreFromBackup: 'Restore from Backup',
  exporting: 'Exporting...',
  restoring: 'Restoring...',
  dataExportedSuccessfully: 'Data exported successfully!',
  dataRestoredSuccessfully: 'Data restored successfully! Please restart the app.',
  failedToExportData: 'Failed to export data',
  failedToRestoreData: 'Failed to restore data',
  errorExportingData: 'Error exporting data',
  errorRestoringData: 'Error restoring data',
  invalidBackupFile: 'Invalid backup file format',
  exportDataDescription: 'Export all your data or restore from a backup file.',
  restoreConfirmation: 'Type "CONFIRM" to restore data (this will delete all current data)',
  confirmationPlaceholder: 'Type CONFIRM here',
  confirmationRequired: 'You must type CONFIRM to proceed',
  nukeDatabase: 'Clear All Data',
  nukeDatabaseConfirmation: 'Type "NUKE" to permanently delete ALL data (this cannot be undone)',
  nukeDatabaseSuccessfully: 'All data cleared successfully!',
  failedToNukeDatabase: 'Failed to clear database',
  errorNukingDatabase: 'Error clearing database',
  nukeDatabaseDescription: 'Permanently delete all recipes, ingredients, and relationships.',
  nuking: 'Clearing...',
}

export default EnglishTranslations
