import { TranslationKeys } from './types'

const EnglishTranslations: Record<TranslationKeys, string> = {
  // General
  loading: 'Loading...',
  error: 'Error',
  welcome: 'Welcome!',
  cancel: 'Cancel',
  save: 'Save',
  update: 'Update',
  add: 'Add',
  delete: 'Delete',
  edit: 'Edit',
  remove: 'Remove',
  close: 'Close',
  confirm: 'Confirm',
  yes: 'Yes',
  no: 'No',
  ok: 'OK',
  actions: 'Actions',
  notes: 'Notes',
  status: 'Status',
  title: 'Title',
  name: 'Name',
  quantity: 'Quantity',
  units: 'Units',
  cost: 'Cost',
  produces: 'Produces',
  settings: 'Settings',
  id: 'ID',
  created: 'Created',
  updated: 'Updated',
  outOf: 'of',
  selected: 'selected',

  // Navigation
  appTitle: 'Menu Engineering',
  recipes: 'Recipes',
  ingredients: 'Ingredients',
  recipe: 'Recipe',
  ingredient: 'Ingredient',

  // Recipe Management
  recipeName: 'Recipe Name',
  ingredientName: 'Ingredient Name',
  addNewRecipe: 'Add New Recipe',
  addNewIngredient: 'Add New Ingredient',
  addRecipe: 'Add Recipe',
  addIngredient: 'Add Ingredient',
  editRecipe: 'Edit Recipe',
  editIngredient: 'Edit Ingredient',
  editIngredients: 'Edit Ingredients',
  updateRecipe: 'Update Recipe',
  updateIngredient: 'Update Ingredient',
  deleteRecipe: 'Delete Recipe',
  removeFromRecipe: 'Remove from Recipe',
  addExisting: 'Add Existing',
  addAnother: 'Add Another',
  saveAndAddAnother: 'Save & Add another',
  addSubRecipe: 'Add Sub-Recipe',
  subRecipe: 'Sub-Recipe',
  showInMenu: 'Show in Menu',
  selectAllRecipes: 'Select All Recipes',
  recipeDetails: 'Recipe Details',
  ingredientDetails: 'Ingredient Details',
  noDetails: 'No Details',
  unitsHelpText: 'Note - Units can only be set on creation',

  // Form Labels and Placeholders
  ingredientNamePlaceholder: 'e.g. Flour, Salt, Olive Oil',
  optionalNotesPlaceholder: 'Optional notes about this ingredient',
  quantityLabel: 'Quantity',
  costLabel: 'Cost',
  producesLabel: 'Produces',
  notesLabel: 'Notes',
  titleLabel: 'Title',
  unitsLabel: 'Units',
  statusLabel: 'Status',

  // Status Values
  draft: 'Draft',
  published: 'Published',
  archived: 'Archived',

  // Messages
  noRecipesFound: 'No recipes found.',
  noIngredientsFound: 'No ingredients found.',
  noDataAvailable: 'No data available.',
  recipeNotFound: 'Recipe not found.',
  errorLoadingRecipe: 'Error loading recipe.',
  errorLoadingRecipes: 'Error loading recipes.',
  errorLoadingIngredients: 'Error loading ingredients.',
  addFirstRecipe: 'Add your first recipe',
  addFirstIngredient: 'Add your first ingredient',
  failedToRemoveIngredient: 'Failed to remove ingredient from recipe.',
  errorRemovingIngredient: 'Error removing ingredient from recipe.',
  failedToAddIngredient: 'Failed to add ingredient.',
  errorAddingIngredient: 'Error adding ingredient.',

  // Loading States
  adding: 'Adding...',
  saving: 'Saving...',
  updating: 'Updating...',
  removing: 'Removing...',

  // Tooltips and Labels
  expandRow: 'expand row',
  editRecipeDetails: 'Edit Recipe Details',
  editIngredientDetails: 'Edit Ingredient Details',
  removeIngredientFromRecipe: 'Remove from Recipe',
  addIngredientTooltip: 'Add Ingredient',
  addRecipeTooltip: 'Add Recipe',
  deleteTooltip: 'Delete',

  // Table Headers
  ingredientDetailsTable: 'ingredient details',

  // Modal Titles
  addNewRecipeModalTitle: 'Add New Recipe',
  addNewIngredientModalTitle: 'Add New Ingredient',
  editRecipeModalTitle: 'Edit Recipe',
  editIngredientModalTitle: 'Edit Ingredient',
  addSubRecipeModalTitle: 'Add New Sub-Recipe',

  // Units
  liters: 'Liters',
  milliliters: 'Milliliters',
  gallons: 'Gallons',
  cups: 'Cups',
  grams: 'Grams',
  kilograms: 'Kilograms',
  ounces: 'Ounces',
  pounds: 'Pounds',
  pieces: 'Pieces',
  weightConversions: 'Weight Conversion Table',
  volumeConversions: 'Volume Conversion Table',
  unitConversions: 'Unit Conversion Tables',
  conversionDisclaimer:
    'Conversions are approximate and based on US standard measurements',

  // Missing translations
  noNotes: 'No notes',
  language: 'Language',
  english: 'English',
  spanish: 'Spanish',
  recipeAddedSuccessfully: 'Recipe added successfully!',
  failedToAddRecipe: 'Failed to add recipe.',
  errorAddingRecipe: 'Error adding recipe.',
  subRecipeAddedSuccessfully: 'Sub-recipe added successfully!',
  failedToAddSubRecipe: 'Failed to add sub-recipe.',
  errorAddingSubRecipe: 'Error adding sub-recipe.',
  recipeUpdatedSuccessfully: 'Recipe updated successfully!',
  failedToUpdateRecipe: 'Failed to update recipe.',
  errorUpdatingRecipe: 'Error updating recipe.',
  ingredientUpdatedSuccessfully: 'Ingredient updated successfully!',
  failedToUpdateIngredient: 'Failed to update ingredient.',
  errorUpdatingIngredient: 'Error updating ingredient.',
  ingredientAddedSuccessfully: 'Ingredient added successfully!',
  filters: 'Filters',
  all: 'All',
}

export default EnglishTranslations
