import { type TranslationKeys } from './types'

const SpanishTranslations: Record<TranslationKeys, string> = {
  // General
  loading: 'Cargando...',
  error: 'Error',
  welcome: '¡Bienvenido!',
  cancel: 'Cancelar',
  save: 'Guardar',
  update: 'Actualizar',
  add: 'Agregar',
  delete: 'Eliminar',
  edit: 'Editar',
  remove: 'Quitar',
  close: 'Cerrar',
  confirm: 'Confirmar',
  yes: 'Sí',
  no: 'No',
  ok: 'OK',
  actions: 'Acciones',
  status: 'Estado',
  title: 'Título',
  name: 'Nombre',
  quantity: 'Cantidad',
  units: 'Unidades',
  cost: 'Costo',
  produces: 'Produce',
  settings: 'Configuraciones',
  id: 'ID',
  created: 'Creado',
  updated: 'Actualizado',
  outOf: 'de',
  selected: 'seleccionado',
  unitCost: 'Costo Unitario',
  totalCost: 'Costo Total',

  // Navigation
  appTitle: 'Ingeniería de Menú',
  recipes: 'Recetas',
  ingredients: 'Ingredientes',
  recipe: 'Receta',
  ingredient: 'Ingrediente',

  // Recipe Management
  recipeName: 'Nombre de Receta',
  ingredientName: 'Nombre de Ingrediente',
  addNewRecipe: 'Agregar Nueva Receta',
  addNewIngredient: 'Agregar Nuevo Ingrediente',
  addRecipe: 'Agregar Receta',
  addIngredient: 'Agregar Ingrediente',
  editRecipe: 'Editar Receta',
  editIngredient: 'Editar Ingrediente',
  editIngredients: 'Editar Ingredientes',
  updateRecipe: 'Actualizar Receta',
  updateIngredient: 'Actualizar Ingrediente',
  deleteRecipe: 'Eliminar Receta',
  removeFromRecipe: 'Quitar de Receta',
  addExisting: 'Agregar Existente',
  addAnother: 'Agregar Otro',
  saveAndAddAnother: 'Guardar y Agregar otro',
  addSubRecipe: 'Agregar Sub-Receta',
  subRecipe: 'Sub-Receta',
  showInMenu: 'Mostrar en Menú',
  selectAllRecipes: 'Seleccionar Todas las Recetas',
  recipeDetails: 'Detalles de Receta',
  ingredientDetails: 'Detalles de Ingrediente',
  noDetails: 'Sin detalles',
  unitsHelpText: 'Nota - Las unidades solo se pueden establecer al crear',
  usedIn: 'Usado en',

  // Form Labels and Placeholders
  ingredientNamePlaceholder: 'ej. Harina, Sal, Aceite de Oliva',
  quantityLabel: 'Cantidad',
  costLabel: 'Costo',
  producesLabel: 'Produce',
  titleLabel: 'Título',
  unitsLabel: 'Unidades',
  statusLabel: 'Estado',

  // Status Values
  draft: 'Borrador',
  published: 'Publicado',
  archived: 'Archivado',

  // Messages
  noRecipesFound: 'No se encontraron recetas.',
  noIngredientsFound: 'No se encontraron ingredientes.',
  noDataAvailable: 'No hay datos disponibles.',
  recipeNotFound: 'Receta no encontrada.',
  ingredientNotFound: 'Ingrediente no encontrado.',
  errorLoadingRecipe: 'Error cargando receta.',
  errorLoadingRecipes: 'Error cargando recetas.',
  errorLoadingIngredients: 'Error cargando ingredientes.',
  addFirstRecipe: 'Agrega tu primera receta',
  addFirstIngredient: 'Agrega tu primer ingrediente',
  failedToRemoveIngredient: 'Falló al quitar ingrediente de la receta.',
  errorRemovingIngredient: 'Error quitando ingrediente de la receta.',
  failedToAddIngredient: 'Falló al agregar ingrediente.',
  errorAddingIngredient: 'Error agregando ingrediente.',

  // Loading States
  adding: 'Agregando...',
  saving: 'Guardando...',
  updating: 'Actualizando...',
  removing: 'Quitando...',

  // Tooltips and Labels
  expandRow: 'expandir fila',
  editRecipeDetails: 'Editar Detalles de Receta',
  editIngredientDetails: 'Editar Detalles de Ingrediente',
  removeIngredientFromRecipe: 'Quitar de Receta',
  addIngredientTooltip: 'Agregar Ingrediente',
  addRecipeTooltip: 'Agregar Receta',
  deleteTooltip: 'Eliminar',

  // Table Headers
  ingredientDetailsTable: 'detalles de ingredientes',

  // Modal Titles
  addNewRecipeModalTitle: 'Agregar Nueva Receta',
  addNewIngredientModalTitle: 'Agregar Nuevo Ingrediente',
  editRecipeModalTitle: 'Editar Receta',
  editIngredientModalTitle: 'Editar Ingrediente',
  addSubRecipeModalTitle: 'Agregar Nueva Sub-Receta',

  // Units
  units_singular: 'Unidad',
  units_plural: 'Unidades',
  liters_singular: 'Litro',
  liters_plural: 'Litros',
  milliliters_singular: 'Mililitro',
  milliliters_plural: 'Mililitros',
  gallons_singular: 'Galón',
  gallons_plural: 'Galones',
  cups_singular: 'Taza',
  cups_plural: 'Tazas',
  grams_singular: 'Gramo',
  grams_plural: 'Gramos',
  kilograms_singular: 'Kilogramo',
  kilograms_plural: 'Kilogramos',
  ounces_singular: 'Onza',
  ounces_plural: 'Onzas',
  pounds_singular: 'Libra',
  pounds_plural: 'Libras',
  pieces_singular: 'Pieza',
  pieces_plural: 'Piezas',
  weightConversions: 'Tabla de Conversión de Peso',
  volumeConversions: 'Tabla de Conversión de Volumen',
  unitConversions: 'Conversión de Unidades',
  conversionDisclaimer:
    'Las conversiones son aproximadas y se basan en medidas estándar de EE.UU.',

  // Missing translations
  language: 'Idioma',
  english: 'Inglés',
  spanish: 'Español',
  recipeAddedSuccessfully: '¡Receta agregada exitosamente!',
  failedToAddRecipe: 'Falló al agregar receta.',
  errorAddingRecipe: 'Error agregando receta.',
  subRecipeAddedSuccessfully: '¡Sub-receta agregada exitosamente!',
  failedToAddSubRecipe: 'Falló al agregar sub-receta.',
  errorAddingSubRecipe: 'Error agregando sub-receta.',
  recipeUpdatedSuccessfully: '¡Receta actualizada exitosamente!',
  failedToUpdateRecipe: 'Falló al actualizar receta.',
  errorUpdatingRecipe: 'Error actualizando receta.',
  ingredientUpdatedSuccessfully: '¡Ingrediente actualizado exitosamente!',
  failedToUpdateIngredient: 'Falló al actualizar ingrediente.',
  errorUpdatingIngredient: 'Error actualizando ingrediente.',
  ingredientAddedSuccessfully: '¡Ingrediente agregado exitosamente!',
  filters: 'Filtros',
  all: 'Todos',
}

export default SpanishTranslations
