import type { TranslationKeys } from './types'

const SpanishTranslations: Record<TranslationKeys, string> = {
  RECIPE_EXISTS: 'La receta ya existe.',
  INGREDIENT_EXISTS: 'El ingrediente ya existe.',
  SOMETHING_WENT_WRONG: 'Algo salió mal. Por favor, inténtalo de nuevo.',

  // General
  save: 'Guardar',
  add: 'Agregar',
  edit: 'Editar',
  delete: 'Eliminar',
  export: 'Exportar',
  remove: 'Quitar',
  update: 'Actualizar',
  cancel: 'Cancelar',
  yes: 'Sí',
  no: 'No',
  loading: 'Cargando...',
  filename: 'Nombre de archivo',
  status: 'Estado',
  title: 'Título',
  quantity: 'Cantidad',
  units: 'Unidades',
  cost: 'Costo',
  produces: 'Produce',
  settings: 'Configuraciones',
  created: 'Creado',
  outOf: 'de',
  unitCost: 'Costo Unitario',
  totalCost: 'Total',
  includeImages: 'Incluir Imágenes',
  oneFilePerRecipe: 'Un Archivo por Receta',
  searchRecipes: 'Buscar recetas...',
  searchIngredients: 'Buscar ingredientes...',
  all: 'Todos',
  none: 'Ninguno',
  singlePDF: 'PDF Único',
  multiplePDFs: 'Múltiples PDFs',
  select: 'Seleccionar',

  // Navigation
  recipes: 'Recetas',
  ingredients: 'Ingredientes',
  recipe: 'Receta',
  ingredient: 'Ingrediente',

  // Recipe Management
  noDataAvailable: 'No hay datos disponibles',
  recipeName: 'Nombre de Receta',
  ingredientName: 'Nombre de Ingrediente',
  addNewRecipe: 'Agregar Nueva Receta',
  addNewIngredient: 'Agregar Nuevo Ingrediente',
  addRecipe: 'Agregar Receta',
  addIngredient: 'Agregar Ingrediente',
  editRecipe: 'Editar Receta',
  deleteRecipe: 'Eliminar Receta',
  deleteIngredient: 'Eliminar Ingrediente',
  confirmDeleteRecipe: 'Confirmar Eliminar Receta',
  confirmDeleteIngredient: 'Confirmar Eliminar Ingrediente',
  deleteRecipeConfirmation: '¿Estás seguro de que quieres eliminar esta receta? Esta acción no se puede deshacer.',
  deleteIngredientConfirmation:
    '¿Estás seguro de que quieres eliminar este ingrediente? Esta acción no se puede deshacer.',
  editIngredient: 'Editar Ingrediente',
  viewRecipe: 'Ver Receta',
  addExisting: 'Agregar Existente',
  saveAndAddAnother: 'Guardar y Agregar otro',
  addSubRecipe: 'Agregar Sub-Receta',
  showInMenu: 'En Menú',
  filterToMenuItems: 'Solo platos del menú',
  subRecipes: 'Sub Recetas',
  mainRecipes: 'Recetas',
  noDetails: 'Sin detalles',
  usedIn: 'Usado en',
  addToRecipe: 'Agregar componente',
  recipeUses: 'Receta utiliza',
  close: 'Cerrar',

  // Form Labels and Placeholders
  ingredientNamePlaceholder: 'ej. Harina, Sal, Aceite de Oliva',

  // Status Values
  draft: 'Borrador',
  published: 'Publicado',
  archived: 'Archivado',

  // Messages
  recipeNotFound: 'Receta no encontrada.',
  ingredientNotFound: 'Ingrediente no encontrado.',
  errorLoadingRecipe: 'Error cargando receta.',
  errorLoadingRecipes: 'Error cargando recetas.',
  errorLoadingIngredients: 'Error cargando ingredientes.',
  failedToAddIngredient: 'Falló al agregar ingrediente.',
  errorAddingIngredient: 'Error agregando ingrediente.',

  // Loading States
  adding: 'Agregando...',
  saving: 'Guardando...',
  updating: 'Actualizando...',

  // Units
  units_singular: 'Unidad',
  units_plural: 'Unidades',
  units_abbreviated: 'unidad',
  liters_singular: 'Litro',
  liters_plural: 'Litros',
  liters_abbreviated: 'L',
  milliliters_singular: 'Mililitro',
  milliliters_plural: 'Mililitros',
  milliliters_abbreviated: 'ml',
  gallons_singular: 'Galón',
  gallons_plural: 'Galones',
  gallons_abbreviated: 'Gl',
  cups_singular: 'Taza',
  cups_plural: 'Tazas',
  cups_abbreviated: 'Tz',
  milligrams_singular: 'Miligramo',
  milligrams_plural: 'Miligramos',
  milligrams_abbreviated: 'mg',
  grams_singular: 'Gramo',
  grams_plural: 'Gramos',
  grams_abbreviated: 'g',
  kilograms_singular: 'Kilogramo',
  kilograms_plural: 'Kilogramos',
  kilograms_abbreviated: 'kg',
  ounces_singular: 'Onza',
  ounces_plural: 'Onzas',
  ounces_abbreviated: 'oz',
  pounds_singular: 'Libra',
  pounds_plural: 'Libras',
  pounds_abbreviated: 'lb',
  pieces_singular: 'Pieza',
  pieces_plural: 'Piezas',
  pieces_abbreviated: 'Pz',
  weight: 'Peso',
  volume: 'Volumen',
  weightConversions: 'Tabla de Conversión de Peso',
  volumeConversions: 'Tabla de Conversión de Volumen',
  unitConversions: 'Conversión de Unidades',

  // Missing translations
  language: 'Idioma',
  english: 'Inglés',
  spanish: 'Español',
  country: 'País',
  internationalization: 'Internacionalización',
  data: 'Datos',
  errorAddingRecipe: 'Error agregando receta.',
  errorAddingSubRecipe: 'Error agregando sub-receta.',
  failedToUpdateRecipe: 'Falló al actualizar receta.',
  errorUpdatingRecipe: 'Error actualizando receta.',
  failedToUpdateIngredient: 'Falló al actualizar ingrediente.',
  errorUpdatingIngredient: 'Error actualizando ingrediente.',

  // Data Management
  dataManagement: 'Gestión de Datos',
  databaseBackups: 'Copias de Seguridad de Base de Datos',
  backupLocation: 'Ubicación de copia de seguridad',
  exportAllData: 'Exportar Todos los Datos',
  restoreFromBackup: 'Restaurar desde Copia de Seguridad',
  exporting: 'Exportando...',
  restoring: 'Restaurando...',
  dataExportedSuccessfully: '¡Datos exportados exitosamente!',
  dataRestoredSuccessfully: '¡Datos restaurados exitosamente! Por favor reinicia la aplicación.',
  failedToExportData: 'Falló al exportar datos',
  failedToRestoreData: 'Falló al restaurar datos',
  errorExportingData: 'Error exportando datos',
  errorRestoringData: 'Error restaurando datos',
  invalidBackupFile: 'Formato de archivo de copia de seguridad inválido',
  exportDataDescription: 'Exporta todos tus datos o restaura desde un archivo de copia de seguridad.',
  restoreConfirmation: 'Escribe "CONFIRMAR" para restaurar datos (esto eliminará todos los datos actuales)',
  confirmationPlaceholder: 'Escribe CONFIRMAR aquí',
  confirmationRequired: 'Debes escribir CONFIRMAR para continuar',
  nukeDatabase: 'Eliminar Todos los Datos',
  nukeDatabaseConfirmation:
    'Escribe "ELIMINAR" para borrar permanentemente TODOS los datos (esto no se puede deshacer)',
  nukeDatabaseSuccessfully: '¡Todos los datos eliminados exitosamente!',
  failedToNukeDatabase: 'Falló al eliminar base de datos',
  errorNukingDatabase: 'Error eliminando base de datos',
  nukeDatabaseDescription: 'Eliminar permanentemente todas las recetas, ingredientes y relaciones.',
  nuking: 'Eliminando...',

  // Unit Preferences
  unitPreferences: 'Preferencias de Unidades',
  volumeUnits: 'Unidades de Volumen',
  weightUnits: 'Unidades de Peso',
  genericUnits: 'Unidades Genéricas',
  changeSelectedUnits: 'Cambiar unidades seleccionadas',
  modifyUnitsInPreferences:
    "Las unidades se pueden modificar en la pestaña 'Preferencias de Unidades' de Configuraciones.",

  // Changelog
  changelog: 'Registro de cambios',
  whatsNew: 'Novedades',
  gotIt: 'Entendido',
  welcomeToVersion: 'Bienvenido a la versión',
  changelogNew: 'Nuevo',
  changelogImproved: 'Mejorado',
  changelogFixed: 'Corregido',

  // Unit Change Confirmation Modal
  unitChangeConfirmTitle: 'Confirmar Cambio de Unidad',
  unitChangeWarningTitle: 'Advertencia de Cambio de Unidad',
  unitChangeItemInfo: '¿Cambiar "{{itemName}}" de {{fromUnit}} a {{toUnit}}?',
  unitCostConversionPreview: 'El costo unitario se convertirá:',
  unitChangeRecipeCompatibleInfo: 'El valor de producción permanecerá sin cambios.',
  unitChangeWarning: 'Cambio de unidad incompatible',
  unitChangeIncompatibleIngredientInfo:
    'La cantidad se restablecerá a 0 en todas las recetas que usan este ingrediente.',
  unitChangeIncompatibleRecipeInfo:
    'La cantidad se restablecerá a 0 en todas las recetas que usan esto como sub-receta.',
  unitChangeAffectedItems: 'Recetas afectadas ({{count}}):',
  unitChangeAndMore: '...y {{count}} más',
  unitChangeConfirmButton: 'Cambiar Unidades',

  // Warnings
  recipeHasZeroQuantity: 'La receta contiene ingredientes o sub-recetas con cantidad 0',

  // Recent Items Sidebar
  recentItems: 'Recientes',
  pinnedItems: 'Fijados',
  pinRecipe: 'Fijar receta',
  unpinRecipe: 'Desfijar receta',
  noRecentItems: 'No hay recetas recientes',
  clearAll: 'Borrar todo',
  removeFromRecent: 'Quitar',

  // Recipe Detail Page
  backToRecipes: 'Volver a Recetas',

  // Ingredient Detail Page
  backToIngredients: 'Volver a Ingredientes',
  viewIngredient: 'Ver Ingrediente',
}

export default SpanishTranslations
