import type { ERROR_CODES } from '../../shared/errorCodes'

export type TranslationKeys =
  | keyof typeof ERROR_CODES
  | 'save'
  | 'add'
  | 'edit'
  | 'delete'
  | 'remove'
  | 'update'
  | 'cancel'
  | 'loading'
  | 'export'
  | 'yes'
  | 'no'
  | 'status'
  | 'title'
  | 'quantity'
  | 'filename'
  | 'units'
  | 'cost'
  | 'produces'
  | 'settings'
  | 'created'
  | 'outOf'
  | 'unitCost'
  | 'totalCost'
  | 'usedIn'
  | 'includeImages'
  | 'oneFilePerRecipe'
  | 'singlePDF'
  | 'multiplePDFs'
  | 'searchRecipes'
  | 'searchIngredients'
  | 'subRecipes'
  | 'mainRecipes'
  | 'country'
  | 'weight'
  | 'volume'
  | 'internationalization'
  | 'data'

  // Navigation
  | 'recipes'
  | 'ingredients'
  | 'recipe'
  | 'ingredient'

  // Recipe Management
  | 'noDataAvailable'
  | 'noDetails'
  | 'recipeName'
  | 'ingredientName'
  | 'addNewRecipe'
  | 'addNewIngredient'
  | 'addRecipe'
  | 'addIngredient'
  | 'editRecipe'
  | 'deleteRecipe'
  | 'deleteIngredient'
  | 'confirmDeleteRecipe'
  | 'confirmDeleteIngredient'
  | 'deleteRecipeConfirmation'
  | 'deleteIngredientConfirmation'
  | 'editIngredient'
  | 'viewRecipe'
  | 'addExisting'
  | 'saveAndAddAnother'
  | 'addSubRecipe'
  | 'showInMenu'
  | 'filterToMenuItems'
  | 'addToRecipe'
  | 'recipeUses'
  | 'close'

  // Form Labels and Placeholders
  | 'ingredientNamePlaceholder'

  // Status Values
  | 'draft'
  | 'published'
  | 'archived'

  // Messages
  | 'recipeNotFound'
  | 'ingredientNotFound'
  | 'errorLoadingRecipe'
  | 'errorLoadingRecipes'
  | 'errorLoadingIngredients'
  | 'failedToAddIngredient'
  | 'errorAddingIngredient'

  // Loading States
  | 'adding'
  | 'saving'
  | 'updating'

  // Units
  | 'units_singular'
  | 'units_plural'
  | 'units_abbreviated'
  | 'liters_abbreviated'
  | 'liters_singular'
  | 'liters_plural'
  | 'milliliters_singular'
  | 'milliliters_plural'
  | 'milliliters_abbreviated'
  | 'gallons_singular'
  | 'gallons_plural'
  | 'gallons_abbreviated'
  | 'cups_singular'
  | 'cups_plural'
  | 'cups_abbreviated'
  | 'grams_singular'
  | 'grams_plural'
  | 'grams_abbreviated'
  | 'kilograms_singular'
  | 'kilograms_plural'
  | 'kilograms_abbreviated'
  | 'ounces_singular'
  | 'ounces_plural'
  | 'ounces_abbreviated'
  | 'pounds_singular'
  | 'pounds_plural'
  | 'pounds_abbreviated'
  | 'pieces_singular'
  | 'pieces_plural'
  | 'pieces_abbreviated'
  | 'milligrams_singular'
  | 'milligrams_plural'
  | 'milligrams_abbreviated'

  // Missing translations
  | 'language'
  | 'english'
  | 'spanish'
  | 'errorAddingRecipe'
  | 'errorAddingSubRecipe'
  | 'failedToUpdateRecipe'
  | 'errorUpdatingRecipe'
  | 'failedToUpdateIngredient'
  | 'errorUpdatingIngredient'
  | 'weightConversions'
  | 'volumeConversions'
  | 'unitConversions'
  | 'all'
  | 'none'
  | 'select'

  // Data Management
  | 'dataManagement'
  | 'databaseBackups'
  | 'backupLocation'
  | 'exportAllData'
  | 'restoreFromBackup'
  | 'exporting'
  | 'restoring'
  | 'dataExportedSuccessfully'
  | 'dataRestoredSuccessfully'
  | 'failedToExportData'
  | 'failedToRestoreData'
  | 'errorExportingData'
  | 'errorRestoringData'
  | 'invalidBackupFile'
  | 'exportDataDescription'
  | 'restoreConfirmation'
  | 'confirmationPlaceholder'
  | 'confirmationRequired'
  | 'nukeDatabase'
  | 'nukeDatabaseConfirmation'
  | 'nukeDatabaseSuccessfully'
  | 'failedToNukeDatabase'
  | 'errorNukingDatabase'
  | 'nukeDatabaseDescription'
  | 'nuking'

  // Unit Preferences
  | 'unitPreferences'
  | 'volumeUnits'
  | 'weightUnits'
  | 'genericUnits'
  | 'changeSelectedUnits'
  | 'modifyUnitsInPreferences'

  // Changelog
  | 'changelog'
  | 'whatsNew'
  | 'gotIt'
  | 'welcomeToVersion'
  | 'changelogNew'
  | 'changelogImproved'
  | 'changelogFixed'

  // Unit Change Confirmation Modal
  | 'unitChangeConfirmTitle'
  | 'unitChangeWarningTitle'
  | 'unitChangeItemInfo'
  | 'unitCostConversionPreview'
  | 'unitChangeRecipeCompatibleInfo'
  | 'unitChangeWarning'
  | 'unitChangeIncompatibleIngredientInfo'
  | 'unitChangeIncompatibleRecipeInfo'
  | 'unitChangeAffectedItems'
  | 'unitChangeAndMore'
  | 'unitChangeConfirmButton'

  // Warnings
  | 'recipeHasZeroQuantity'

  // Recent Items Sidebar
  | 'recentItems'
  | 'pinnedItems'
  | 'pinRecipe'
  | 'unpinRecipe'
  | 'noRecentItems'
  | 'clearAll'
  | 'removeFromRecent'

  // Recipe Detail Page
  | 'backToRecipes'

  // Ingredient Detail Page
  | 'backToIngredients'
  | 'viewIngredient'
