export type TranslationKeys =
  | 'save'
  | 'add'
  | 'edit'
  | 'remove'
  | 'update'
  | 'cancel'
  | 'loading'
  | 'yes'
  | 'no'
  | 'status'
  | 'title'
  | 'quantity'
  | 'units'
  | 'cost'
  | 'produces'
  | 'settings'
  | 'created'
  | 'outOf'
  | 'unitCost'
  | 'totalCost'
  | 'usedIn'

  // Navigation
  | 'recipes'
  | 'ingredients'
  | 'recipe'
  | 'ingredient'

  // Recipe Management
  | 'noDetails'
  | 'recipeName'
  | 'ingredientName'
  | 'addNewRecipe'
  | 'addNewIngredient'
  | 'addRecipe'
  | 'addIngredient'
  | 'editRecipe'
  | 'editIngredient'
  | 'editIngredients'
  | 'addExisting'
  | 'saveAndAddAnother'
  | 'addSubRecipe'
  | 'showInMenu'
  | 'unitsHelpText'

  // Form Labels and Placeholders
  | 'ingredientNamePlaceholder'

  // Status Values
  | 'draft'
  | 'published'
  | 'archived'

  // Messages
  | 'recipeNotFound'
  | 'ingredientNotFound'
  | 'errorLoadingRecipe'
  | 'errorLoadingRecipes'
  | 'errorLoadingIngredients'
  | 'failedToAddIngredient'
  | 'errorAddingIngredient'

  // Loading States
  | 'adding'
  | 'saving'
  | 'updating'

  // Units
  | 'units_singular'
  | 'units_plural'
  | 'liters_singular'
  | 'liters_plural'
  | 'milliliters_singular'
  | 'milliliters_plural'
  | 'gallons_singular'
  | 'gallons_plural'
  | 'cups_singular'
  | 'cups_plural'
  | 'grams_singular'
  | 'grams_plural'
  | 'kilograms_singular'
  | 'kilograms_plural'
  | 'ounces_singular'
  | 'ounces_plural'
  | 'pounds_singular'
  | 'pounds_plural'
  | 'pieces_singular'
  | 'pieces_plural'

  // Missing translations
  | 'language'
  | 'english'
  | 'spanish'
  | 'failedToAddRecipe'
  | 'errorAddingRecipe'
  | 'failedToAddSubRecipe'
  | 'errorAddingSubRecipe'
  | 'failedToUpdateRecipe'
  | 'errorUpdatingRecipe'
  | 'failedToUpdateIngredient'
  | 'errorUpdatingIngredient'
  | 'weightConversions'
  | 'volumeConversions'
  | 'unitConversions'
  | 'conversionDisclaimer'
  | 'all'
