export type TranslationKeys =
  // General
  | 'loading'
  | 'error'
  | 'welcome'
  | 'cancel'
  | 'save'
  | 'update'
  | 'add'
  | 'delete'
  | 'edit'
  | 'remove'
  | 'close'
  | 'confirm'
  | 'yes'
  | 'no'
  | 'ok'
  | 'actions'
  | 'notes'
  | 'status'
  | 'title'
  | 'name'
  | 'quantity'
  | 'units'
  | 'cost'
  | 'produces'
  | 'settings'
  | 'id'
  | 'created'
  | 'updated'
  | 'outOf'
  | 'selected'
  | 'unitCost'
  | 'totalCost'

  // Navigation
  | 'appTitle'
  | 'recipes'
  | 'ingredients'
  | 'recipe'
  | 'ingredient'

  // Recipe Management
  | 'noDetails'
  | 'recipeName'
  | 'ingredientName'
  | 'addNewRecipe'
  | 'addNewIngredient'
  | 'addRecipe'
  | 'addIngredient'
  | 'editRecipe'
  | 'editIngredient'
  | 'editIngredients'
  | 'updateRecipe'
  | 'updateIngredient'
  | 'deleteRecipe'
  | 'removeFromRecipe'
  | 'addExisting'
  | 'addAnother'
  | 'saveAndAddAnother'
  | 'addSubRecipe'
  | 'subRecipe'
  | 'showInMenu'
  | 'selectAllRecipes'
  | 'recipeDetails'
  | 'ingredientDetails'
  | 'unitsHelpText'

  // Form Labels and Placeholders
  | 'ingredientNamePlaceholder'
  | 'optionalNotesPlaceholder'
  | 'quantityLabel'
  | 'costLabel'
  | 'producesLabel'
  | 'notesLabel'
  | 'titleLabel'
  | 'unitsLabel'
  | 'statusLabel'

  // Status Values
  | 'draft'
  | 'published'
  | 'archived'

  // Messages
  | 'noRecipesFound'
  | 'noIngredientsFound'
  | 'noDataAvailable'
  | 'recipeNotFound'
  | 'errorLoadingRecipe'
  | 'errorLoadingRecipes'
  | 'errorLoadingIngredients'
  | 'addFirstRecipe'
  | 'addFirstIngredient'
  | 'failedToRemoveIngredient'
  | 'errorRemovingIngredient'
  | 'failedToAddIngredient'
  | 'errorAddingIngredient'

  // Loading States
  | 'adding'
  | 'saving'
  | 'updating'
  | 'removing'

  // Tooltips and Labels
  | 'expandRow'
  | 'editRecipeDetails'
  | 'editIngredientDetails'
  | 'removeIngredientFromRecipe'
  | 'addIngredientTooltip'
  | 'addRecipeTooltip'
  | 'deleteTooltip'

  // Table Headers
  | 'ingredientDetailsTable'

  // Modal Titles
  | 'addNewRecipeModalTitle'
  | 'addNewIngredientModalTitle'
  | 'editRecipeModalTitle'
  | 'editIngredientModalTitle'
  | 'addSubRecipeModalTitle'

  // Units
  | 'liters'
  | 'milliliters'
  | 'gallons'
  | 'cups'
  | 'grams'
  | 'kilograms'
  | 'ounces'
  | 'pounds'
  | 'pieces'

  // Missing translations
  | 'noNotes'
  | 'language'
  | 'english'
  | 'spanish'
  | 'recipeAddedSuccessfully'
  | 'failedToAddRecipe'
  | 'errorAddingRecipe'
  | 'subRecipeAddedSuccessfully'
  | 'failedToAddSubRecipe'
  | 'errorAddingSubRecipe'
  | 'recipeUpdatedSuccessfully'
  | 'failedToUpdateRecipe'
  | 'errorUpdatingRecipe'
  | 'ingredientUpdatedSuccessfully'
  | 'failedToUpdateIngredient'
  | 'errorUpdatingIngredient'
  | 'ingredientAddedSuccessfully'
  | 'weightConversions'
  | 'volumeConversions'
  | 'unitConversions'
  | 'conversionDisclaimer'
  | 'filters'
  | 'all'
